application_port: 8080
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
  require_ssl: false
email_client:
  sender_api_url: "localhost"
  sender: "amrx101@gmail.com"
  authorization_token: "test"
  timeout_milli: 1000
application:
  port: 8080
  host: "127.0.0.1"
